name: Build dashboard
on:
  push:
  schedule:
    - cron: '12 1 * * *'


env:
  GF_PATH: /home/runner/work/gf-dashboard/gf-dashboard/fonts
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Write out secret
      run: echo "${{ secrets.GF_PUSH_CONFIG }}" | base64 -d > ~/.gf_push_config.ini

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Setup requirements
      run: pip3 install -r requirements.txt
    - name: Clone google/fonts
      uses: actions/checkout@v4
      with:
        repository: google/fonts
        path: fonts
    - name: Run dashboard builder
      run: python3 dashboard.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit downloaded fonts and data
      with:
        file_pattern: 'docs'
