name: Build dashboard
on:
  - push
  - schedule:
    - cron: '12 1 * * *'


env:
  GF_PATH: fonts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Setup requirements
      run: pip3 install -r requirements.txt
    - name: Clone google/fonts
      uses: actions/checkout@v4
      with:
        repository: google/fonts
        path: fonts
    - name: Run dashboard builder
      run: python3 dashboard.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit downloaded fonts and data

